steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/bipinupd/dataflow-code.git']
  id: 'check-out-source-code'
- name: gcr.io/cloud-builders/mvn
  args: ['package']
  dir: '$REPO_NAME'
  id: 'build-jar'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'target/word-count-beam*.jar', 'gs://${_ARTIFACT_REPO}/dataflow_deployment_$BUILD_ID.jar']
  dir: '$REPO_NAME'
  id: 'deploy-jar'
