steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/bipinupd/dataflow-code.git']
  id: 'Checkout source code'
- name: gcr.io/cloud-builders/mvn
  args: ['clean', 'install']
  dir: '$REPO_NAME'
  id: 'Build jar & Run unit test'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://bipin-dev-artifacts/test-pipeline/*.jar', 'gs://bipin-dev-artifacts/test-pipeline/archive/']
  dir: '$REPO_NAME'
  id: 'Move old jar to archive'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'target/word-count-beam*.jar', 'gs://${_ARTIFACT_REPO}/dataflow_deployment_$BUILD_ID.jar']
  dir: '$REPO_NAME'
  id: 'Copy current artifact'
